language: node_js
node_js:
  - 10

install:
  - npm ci # Install npm packages
    #  - npx ganache-cli --gasLimit 8000000 2> /dev/null 1> /dev/null &
  - set -e # Exit immediately if a command exits with a non-zero status

script:
  - npx prettier --check . # Run prettier to ensure consistent formatting
